using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("1.0.0.6")]
[assembly: AssemblyFileVersion("1.0.0.6")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTitle("FieldFinder")]
[assembly: AssemblyDescription("The Field Finder solution allows you to extract certain text from a document's OCR text field and populate that text in specified workspace fields.")]
[assembly: AssemblyCompany("kCura LLC")]
[assembly: AssemblyProduct("Template")]

