using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2015, kCura LLC")]
[assembly: AssemblyTitleAttribute("Template")]
[assembly: AssemblyDescriptionAttribute("Tools to help build source code for kCura repositories.")]
[assembly: AssemblyCompanyAttribute("kCura LLC")]
[assembly: AssemblyProductAttribute("Template")]

